In [1]:
from __future__ import print_function
import torch

In [19]:
x = torch.empty(5, 3)
print(x)

tensor([[2.1184e+07, 3.0690e-41, 1.5870e+07],
        [3.0690e-41, 1.1210e-43, 0.0000e+00],
        [8.9683e-44, 0.0000e+00, 3.7655e+06],
        [3.0690e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [21]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5661, 0.6157, 0.4570],
        [0.8532, 0.0585, 0.4074],
        [0.0560, 0.6572, 0.8572],
        [0.8130, 0.7308, 0.6859],
        [0.5117, 0.4316, 0.0705]])


In [28]:
input = torch.rand(1, 10)
print(input)

tensor([[0.1353, 0.5182, 0.9053, 0.8144, 0.0803, 0.4774, 0.9143, 0.0967, 0.4109,
         0.3681]])


In [31]:
type(input.view(5, -1))

torch.Tensor