# 1. Collaborative Filtering, Kernels, Linear Regression

> In this question, we will use the alternating projections algorithm for low-rank matrix factorization, which aims to minimize

$
J(U, V) = \underbrace{\frac{1}{2}\sum _{(a,i) \in D} (Y_{ai} - [UV^ T]_{ai})^2}_{\text {Squared Error}} + \underbrace{\frac{\lambda }{2}\sum _{a=1}^ n \sum _{j=1}^ k U_{aj}^2 + \frac{\lambda }{2}\sum _{i=1}^ m \sum _{j=1}^ k V_{ij}^2}_{\text {Regularization}}.
$

> In the following, we will call the first term the squared error term, and the two terms with  𝜆  the regularization terms.

> Let  𝑌  be defined as

$
Y = \begin{bmatrix}  5 &  ? &  7 \\ ? &  2 &  ? \\ 4 &  ? &  ? \\ ? &  3 &  6 \\ \end{bmatrix}
$


$D$ is defined as the set of indices  $(a, i)$ , where  $Y_{a,i}$  is not missing. In this problem, we let  $k = \lambda =1$ . Additionally, $U$  and  $V$  are initialized as  $U^{(0)}=[6,0,3,6]^ T$ , and  $V^{(0)}=[4,2,1]^ T$ .

## 1. (a)

Compute $X$ , the matrix of predicted rankings $U V^ T$ given the initial values for $U$ and $V$.

In [2]:
import numpy as np

In [3]:
U_0 = np.array([6,0,3,6])

In [4]:
U_0

array([6, 0, 3, 6])

In [12]:
V_0 = np.array([4,2,1])

In [13]:
V_0

array([4, 2, 1])

In [14]:
X = np.outer(U_0, V_0)

In [11]:
X

array([[24, 12,  6],
       [ 0,  0,  0],
       [12,  6,  3],
       [24, 12,  6]])

In [66]:
Y = np.array([[5,"",7],["",2,""],[4,"",""],["",3,6]] )

In [67]:
Y

array([['5', '', '7'],
       ['', '2', ''],
       ['4', '', ''],
       ['', '3', '6']], dtype='<U21')

In [72]:
row = Y.shape[0]
col = Y.shape[1]
squared_error = 0.0

for a in range(row):
    for i in range(col):
        if Y[a][i] != "":
            squared_error += (int(Y[a][i]) - int(X[a][i]))**2

squared_error = squared_error/2
print(squared_error)

255.5


In [81]:
row = Y.shape[0]
col = Y.shape[1]
regularization_1 = 0.0
regularization_2 = 0.0

for a in range(row):
    regularization_1 += U_0[a]**2

for i in range(col):
    regularization_2 += V_0[i]**2
    
regularization = (regularization_1 + regularization_2)/2
regularization

51.0

## 1. (c)

Suppose  $𝑉$  is kept fixed. Run one step of the algorithm to find the new estimate $U^{(1)}$.

Enter the  $U^{(1)}$  as a list of numbers,  $[U_1^{(1)}, U_2^{(1)}, U_3^{(1)}, U_4^{(1)}]$ :